Shortcut exit link 2393
AppFlowy-IO/appflowy-editor pull request #124
Opened 2023-05-16 19:57 UTC by vincenzoursano

- Press ESC to exit the link editing mode without saving the entered text if any.
- Press ESC again to close up the link menu.

https://github.com/AppFlowy-IO/AppFlowy/issues/2393

@annieappflowy

2023-05-16 19:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AppFlowy-IO/appflowy-editor?pullRequest=124) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AppFlowy-IO/appflowy-editor?pullRequest=124) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AppFlowy-IO/appflowy-editor?pullRequest=124) it.</sub>

2023-05-17 20:25 UTC, Xazin commented on lib/src/render/link_menu/link_menu.dart
> +      },
Sort `child` last.

2023-05-17 20:26 UTC, Xazin commented on test/render/link_menu/link_menu_test.dart
> +        onDismiss: () {}
Can you add a test case for this?

2023-05-17 20:26 UTC, Xazin commented on lib/src/render/toolbar/toolbar_item.dart
> +            },
```suggestion
            onDismiss: _dismissOverlay,
```

2023-05-18 16:58 UTC, vincenzoursano commented on lib/src/render/toolbar/toolbar_item.dart
> +            },
done

2023-05-18 16:58 UTC, vincenzoursano commented on test/render/link_menu/link_menu_test.dart
> +        onDismiss: () {}
done

2023-05-18 16:58 UTC, vincenzoursano commented on lib/src/render/link_menu/link_menu.dart
> +      },
done

2023-05-18 22:24 UTC, a-wallen commented on lib/src/render/link_menu/link_menu.dart
> +        if (key is! RawKeyDownEvent) return;
```suggestion
        if (key is! RawKeyDownEvent) {
          return;
        }
```
IIRC, Effective Dart says to use curly braces.

2023-05-18 22:30 UTC, a-wallen commented on lib/src/render/link_menu/link_menu.dart
> +          hintText: 'URL',
Please use a translatable string for this hint text. 

https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/translation

See `locale_keys.g.dart`... you can add a key, value pair of your choice to  `en.json` and run a task (control+shift+p, then type task: generate...) to generate the `LocaleKeys`, then you can use it here like so:

```dart
hintText: LocaleKeys.url_label.tr();
```

2023-05-18 22:33 UTC, a-wallen commented on lib/src/render/link_menu/link_menu.dart
> +            borderSide: BorderSide(color: Color(0xFFBDBDBD)),
Please reference a grey color from the app theme. See `color_scheme.dart`. The shaders from `color_scheme` should be approximate.

2023-05-18 22:40 UTC, a-wallen requested changes
Good work so far. Please address my comments at your convenience :)

2023-05-19 17:27 UTC, vincenzoursano commented on lib/src/render/link_menu/link_menu.dart
> +            borderSide: BorderSide(color: Color(0xFFBDBDBD)),
done :)

2023-05-19 17:33 UTC, vincenzoursano commented on lib/src/render/link_menu/link_menu.dart
> +          hintText: 'URL',
Currently, within appflowy-editor, I don't understand how the language management works, and there is a lack of documentation. It's okay to add it to the main project, but I don't understand how to pass it to appflowy-editor. 
Can we do it in a separate pull request so that we can manage all the labels?

2023-05-21 02:37 UTC, a-wallen commented on lib/src/render/link_menu/link_menu.dart
> +          hintText: 'URL',
Let's add internationalization before this pull request lands. You can DM me on discord (a-wallen#0603) if you need help. I'm happy to hop on a call to show you how this is done.

cc @LucasXu0, we might want to add better documentation for internationalization per this comment.

2023-05-22 05:48 UTC, LucasXu0 commented
Hey, @vincenzoursano. Thanks for contributing. would you mind change the merge branch to the mobile?

2023-05-22 05:50 UTC, LucasXu0 commented on lib/src/render/link_menu/link_menu.dart
> +          hintText: 'URL',
Sure. The translation for the editor is different from the main project. Here's the guide link: https://github.com/AppFlowy-IO/appflowy-editor/blob/main/documentation/translation.md

2023-05-23 18:15 UTC, Xazin commented on lib/src/editor/toolbar/items/link/link_menu.dart
> +        }
```suggestion
        if (key is RawKeyDownEvent && key.logicalKey == LogicalKeyboardKey.escape) {
          widget.onDismiss();
        }
```

2023-05-26 19:44 UTC, vincenzoursano commented
Hi @LucasXu0, I changed the merge branch. Do we need to do anything else?

2023-06-05 08:02 UTC, annieappflowy commented
Status?

2023-06-05 20:58 UTC, a-wallen commented
LGTM @annieappflowy, but cc @LucasXu0 because there are no CI workflows running tests.

2023-07-03 09:05 UTC, merged