fix: scroll auto scroll fixes
AppFlowy-IO/appflowy-editor pull request #132
Opened 2023-05-24 04:26 UTC by alihassan143

fix #76

2023-05-24 05:17 UTC, alihassan143 commented
@LucasXu0 @Xazin

2023-05-24 16:59 UTC, Xazin reviewed
Some small comments. Haven't had time to check the logic in-depth.

2023-05-24 16:59 UTC, Xazin commented on lib/src/editor/editor_component/service/ime/delta_input_service.dart
> +  // void insertContent(KeyboardInsertedContent content) {
Uncomment or delete this

2023-05-24 16:59 UTC, Xazin commented on lib/src/editor/editor_component/service/scroll/desktop_scroll_service.dart
> +  bool get implecet => widget.scrollController.position.allowImplicitScrolling;
Shouldn't `implecet` be spelled implicit

2023-05-24 16:59 UTC, Xazin commented on lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
> +    final selectNodes = currentSelectedNodes;
Is there a reason to have `selectNodes` over just accessing `currentSelectedNodes`?

2023-05-24 16:59 UTC, Xazin commented on lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
> +    }
```suggestion
    } else if (rect.bottom <= topLimit && selection.isForward) {
      editorState.service.scrollService?.scrollTo(dy - 10.0);
    }
```

2023-05-24 17:04 UTC, alihassan143 commented on lib/src/editor/editor_component/service/ime/delta_input_service.dart
> +  // void insertContent(KeyboardInsertedContent content) {
i am using latest flutter version and in latest version this method needed to be added to start test the plugin

2023-05-24 17:05 UTC, alihassan143 commented on lib/src/editor/editor_component/service/scroll/desktop_scroll_service.dart
> +  bool get implecet => widget.scrollController.position.allowImplicitScrolling;
ok i will change that

2023-05-24 17:10 UTC, Xazin commented on lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
> +    final double offsetDelta = targetOffset;
You don't need this?

2023-05-24 17:10 UTC, Xazin commented on lib/src/service/input_service.dart
> +  // @override
I assume you can outcomment this

2023-05-24 17:10 UTC, Xazin commented on lib/src/service/scroll_service.dart
> +  bool get implecet;
```suggestion
  bool get implicit;
```
By the name of the variable, I am unsure of its purpose. Maybe we can name it something better?

2023-05-24 17:10 UTC, Xazin commented on pubspec.yaml
> +  url_launcher: ">=6.0.0 <7.0.0"
Did you need to change these? I am not a fan of the version constraints.

2023-05-24 17:10 UTC, Xazin commented on lib/src/render/image/image_node_widget.dart
> +        border: Border.all(width: 1, color: Colors.black),
Don't we have a color for this in editorstyle, if not we should use one from ThemeData or EditorStyle.

2023-05-24 17:10 UTC, Xazin commented on lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
> +      Log.selection
Do we need this Log?

2023-05-24 17:10 UTC, Xazin commented on lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
> +      );
If we do need the Log, then at least:

```suggestion
      final caretOffset = _getOffsetToRevealCaret(cursorRect).offset;
      Log.selection.debug("reveal: $caretOffset");
      editorState.service.scrollService?.scrollController.animateTo(
        caretOffset,
        duration: const Duration(milliseconds: 100),
        curve: Curves.easeIn,
      );
```

2023-05-24 17:13 UTC, Xazin commented on lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
> +    final selectNodes = currentSelectedNodes;
They have the same value.

2023-05-24 17:15 UTC, alihassan143 commented on pubspec.yaml
> +  url_launcher: ">=6.0.0 <7.0.0"
version constraints is good when users used the same dependencies he did'nt get version conflicts errors and we don't have to manually update version every time

2023-05-24 17:17 UTC, alihassan143 commented on lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
> +      );
ok

2023-05-24 17:18 UTC, alihassan143 commented on lib/src/render/image/image_node_widget.dart
> +        border: Border.all(width: 1, color: Colors.black),
i will check and apply accordingly

2023-05-24 17:41 UTC, alihassan143 commented on lib/src/service/input_service.dart
> +  // @override
this class will be deleted because input_service.dart replaced with delta_input_service

2023-05-24 17:42 UTC, alihassan143 commented
@Xazin  i applied changes you asked on some files

2023-05-24 20:24 UTC, LucasXu0 commented
@alihassan143 there is a class called `AutoScroller` available to handle the automatic scroll logic. You can use it instead of re-implementing those logics.

2023-05-24 20:25 UTC, LucasXu0 commented
And please split the different features into different PRs. This is because if you upgrade the Flutter version, you will also need to update AppFlowy.

2023-05-25 04:07 UTC, alihassan143 commented
> And please split the different features into different PRs. This is because if you upgrade the Flutter version, you will also need to update AppFlowy.

currently this pr didn't included upgrade flutter version its working with flutter 3.7

2023-05-25 05:06 UTC, alihassan143 commented
@LucasXu0  i updated the code kindly review it

2023-05-25 17:21 UTC, alihassan143 commented
@LucasXu0

2023-05-26 10:30 UTC, Xazin requested changes

2023-05-26 10:30 UTC, Xazin commented on pubspec.yaml
> +  url_launcher: ">=6.0.0 <7.0.0"
```suggestion
  url_launcher: ^6.0.0
```
Using the caret, this would be equivalent to the version range constraint you changed it to. I honestly prefer `^6.1.11` over this.

2023-05-26 10:37 UTC, alihassan143 commented on pubspec.yaml
> +  flutter_svg: ">=2.0.0 <4.0.0"
ok i will do it

2023-05-26 10:38 UTC, alihassan143 commented on pubspec.yaml
> +  url_launcher: ">=6.0.0 <7.0.0"
ok

2023-05-26 10:38 UTC, alihassan143 commented
@Xazin  changes applied

2023-05-26 12:01 UTC, alihassan143 commented
@LucasXu0 @Xazin

2023-05-26 12:48 UTC, Xazin commented on pubspec.yaml
> +  flutter_svg: ">=2.0.0 <3.0.0"
Still, this is no different from `^2.0.0`, except you also allow other minor versions than `^2.0.6`.

2023-05-26 12:56 UTC, alihassan143 commented
@Xazin now ?

2023-05-27 10:24 UTC, alihassan143 commented
@LucasXu0  @Xazin  can you look into the pr

2023-05-27 14:24 UTC, alihassan143 commented
@LucasXu0 
should i close this pr i think you are working on this issue?

2023-05-27 14:53 UTC, LucasXu0 commented on example/.metadata
> +>>>>>>> upstream/main
there're conflicts. Don't push them.

2023-05-27 14:53 UTC, LucasXu0 commented on example/ios/Runner.xcodeproj/project.pbxproj
> +				"${TARGET_BUILD_DIR}/${INFOPLIST_PATH}",
no need to change it.

2023-05-27 14:53 UTC, LucasXu0 commented on lib/src/editor/editor_component/service/scroll/auto_scroller.dart
I will switch to your branch to modify the logics.

2023-05-27 14:53 UTC, LucasXu0 commented on lib/src/editor/editor_component/service/scroll/auto_scroller.dart
the auto scroller should observe the selection to update the position instead of providing a `scrollOnUpdate` function that let selection_service call.

2023-05-27 14:53 UTC, LucasXu0 commented on lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
> +        () => updateSelection(currentSelection.value!),
I forgot why I commented out those code. :(

2023-05-27 14:53 UTC, LucasXu0 commented on lib/src/render/image/image_node_builder.dart
> +    //some time align attribute is not present from dynamic data so we are adding default value
this file has been deprecated.

2023-05-27 14:53 UTC, LucasXu0 commented on lib/src/render/image/image_node_builder.dart
> +    //some time align attribute is not present from dynamic data so we are adding default value
use `ImageBlockComponentWidget` instead.

2023-05-27 14:55 UTC, LucasXu0 commented
FYI, I will change the code related to the autoscroller later.

Would you mind adding some widget tests to cover your code? Like testing the auto scroller in a long document.

2023-05-29 10:02 UTC, closed without merging