fix: copy handler migrated to latest api
AppFlowy-IO/appflowy-editor pull request #240
Opened 2023-06-22 09:47 UTC by alihassan143

#189

2023-06-22 09:48 UTC, alihassan143 commented
https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/d777f5f0-bd27-492f-b678-ed4291b4ae0d

@LucasXu0

2023-06-22 10:04 UTC, alihassan143 commented
https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/18b5897a-931d-48db-b138-b0f2f588a800

**Macos**

2023-06-22 10:28 UTC, alihassan143 commented
https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/b6ee84d8-8433-44c3-aaa0-2d5b6ce24a47

**Android real device**

2023-06-23 02:04 UTC, LucasXu0 commented
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/b03a8f74-c7b7-48c0-8088-02a3b14d6e5e

@alihassan143 please check this video

2023-06-23 02:42 UTC, alihassan143 commented
@LucasXu0 paste handler is not migrated yeh so i need to migrate the paste handler also

2023-06-23 06:04 UTC, alihassan143 commented
@LucasXu0 copy command handler is  used in desktop for paste text

2023-06-27 06:32 UTC, alihassan143 commented
https://github.com/AppFlowy-IO/assets/71745182/021fbcca-5d72-4504-8b04-0068b44bc3ad

@LucasXu0

2023-06-27 10:10 UTC, alihassan143 commented
@LucasXu0  will you review this now its ready for review

2023-06-27 11:04 UTC, LucasXu0 commented
@alihassan143 Sure. I checked your video and found an issue.

If the text consists of just a single line, we should insert it within the existing paragraph.

For example, ABC|(<- paste a new line here)EFG, the result should be ABCXXXEFG instead of 
ABC
XXX
EFG

2023-06-27 11:16 UTC, alihassan143 commented
> @alihassan143 Sure. I checked your video and found an issue.
> 
> If the text consists of just a single line, we should insert it within the existing paragraph.
> 
> For example, ABC|(<- paste a new line here)EFG, the result should be ABCXXXEFG instead of ABC XXX EFG

its done

2023-06-28 08:45 UTC, LucasXu0 commented
FYI, @alihassan143. It takes time to review. Too many files were modified at once.

2023-07-03 09:48 UTC, alihassan143 commented
https://github.com/AppFlowy-IO@LucasXu0 appflowy-editor/assets/71745182/32948130-230c-49fa-a4db-5f880b2feae2

@LucasXu0 
kindly review this pr

2023-07-05 04:07 UTC, alihassan143 commented
@LucasXu0  pr is ready for review will you review it?

2023-07-05 07:20 UTC, alihassan143 commented
@Xazin  @LucasXu0  changes applied

2023-07-10 10:44 UTC, LucasXu0 commented
Great! I will do some refactor and optimize the logic.

2023-07-12 06:02 UTC, alihassan143 commented
@LucasXu0  this should be included in 1.2 version because lot of things changes but copy paste will not works on 1.2 version

2023-07-20 12:55 UTC, alihassan143 commented
@LucasXu0  you will rebase this or i will try?

2023-07-21 13:31 UTC, MayurSMahajan requested changes

2023-07-21 13:31 UTC, MayurSMahajan commented on test/new/command/copy_command_test.dart
> +  );
@alihassan143 Please check here that when you press backspace, the document is actually cleared.
Meaning that check if document is empty when you select all, and press backspace.

2023-07-21 13:31 UTC, MayurSMahajan commented on test/new/command/copy_command_test.dart
> +      await _testhandleCopy(tester, Document.fromJson(paragraphdata));
Please follow camelCase name convention and rename `_testhandleCopy` to `_testHandleCopy`

2023-07-21 13:31 UTC, MayurSMahajan commented on test/new/command/copy_command_test.dart
> +const paragraphText =
Remove `paragraphText` if you are not using it.

2023-07-21 13:31 UTC, MayurSMahajan commented on test/new/command/cut_command_test.dart
> +      await _testcutHandle(tester, Document.fromJson(paragraphdata));
Please follow camelCase name convention and rename `_testcutHandle` to `_testCutHandle`

2023-07-21 13:31 UTC, MayurSMahajan commented on test/new/command/paste_command_test.dart
> +      await _testhandleCopyPaste(tester, Document.fromJson(paragraphdata));
Camel Case naming convention

2023-07-21 13:31 UTC, MayurSMahajan commented on test/new/command/paste_command_test.dart
> +
Can you write a test to check the document after calling Paste Command multiple times? In fact, you don't need to create new test file, just within this file only, you can press the Paste command again and check if the document gets changed or not.

2023-07-21 19:23 UTC, Xazin approved these changes
Some formatting could be nicer, and some generic syntax.

2023-07-21 19:23 UTC, Xazin commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/cut_command.dart
> +/// Copy.
```suggestion
/// Cut
```

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +}
```suggestion
int _textLengthOfNode(Node node) => node.delta?.length ?? 0;
```

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +  assert(selection.isCollapsed);
Shouldnt this be
```suggestion
  if (selection == null || selection.isCollapsed) {
    return;
  }
```

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +  int lenOfLastNode = _textLengthOfNode(nodes.last);
final

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +  return;
Redundant return

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +  final tb = editorState.transaction;
What is tb? (Hint: better naming)

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +    }
Seems you don't need delta variable much.

```suggestion
    final node = selectionNode.first;
    if (node.delta == null) {
      tb.afterSelection = afterSelection;
      tb.insertNodes(afterSelection.end.path, nodes);
      editorState.apply(tb);
    }
```

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +    return;
Redundant return

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +    return;
```suggestion
    return _pastRichClipboard(editorState, data);
```

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +void _pastRichClipboard(EditorState editorState, AppFlowyClipboardData data) {
```suggestion
void _pasteRichClipboard(EditorState editorState, AppFlowyClipboardData data) {
```

2023-07-21 19:23 UTC, Xazin commented on lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
> +  return;
Redundant return

2023-07-22 12:57 UTC, MayurSMahajan approved these changes

2023-07-25 02:08 UTC, merged