feat: skip whitespace between words while navigating with CTRL+ARROW keys
AppFlowy-IO/appflowy-editor pull request #363
Opened 2023-08-08 10:29 UTC by johansutrisno

linked to https://github.com/AppFlowy-IO/appflowy-editor/issues/344

[FR] Skip whitespace between words while navigating with CTRL+ARROW keys

https://github.com/AppFlowy-IO/appflowy-editor/assets/22239637/5f515d4b-6561-46c1-b67b-cf70a5bcfd21

2023-08-08 11:33 UTC, MayurSMahajan commented
hey @johansutrisno! Thanks for making this PR, would you mind refactoring the failing tests to test the new desired functionalities? They are failing now because CTRL+arrow keys did not skip whitespace before and hence the failing tests don't expect the skips too.

2023-08-08 13:09 UTC, johansutrisno commented
sorry, thank you for reminding me @MayurSMahajan . Sure, I would like to refactoring the failing tests 👌🏼

2023-08-10 07:30 UTC, Xazin commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_left_command.dart
> +    var startOfWord = selection.end.moveHorizontal(
```suggestion
    final startOfWord = selection.end.moveHorizontal(
```

2023-08-11 03:37 UTC, johansutrisno commented
Hi @MayurSMahajan , I have refactored the failing tests, do you have any concern about my changes?

2023-08-11 07:19 UTC, MayurSMahajan commented
Thanks @johansutrisno, let me review your changes.

2023-08-11 10:33 UTC, MayurSMahajan requested changes

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_left_command.dart
> +
`if (node == null || delta == null) {
    return KeyEventResult.ignored;
  }`

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_left_command.dart
> +
check if the `node` or `delta` is not null and thus you won't need to use null check and null assertation operators below

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_left_command.dart
> +    if (selectedWord!.trim().isEmpty) {
no need of null assertion (!) :
`selectedWord`

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_left_command.dart
> +    );
`
if (startOfWord == null) {
      return KeyEventResult.handled;
    }
 `
 we need to check if startOfWord is not null, imagine we were at the start of the line and pressed this key, since there is nothing towards the left, we simply return with handled and skip the unnecessary logic below.

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_left_command.dart
> +    final selectedWord = delta?.toPlainText().substring(
delta

no need for delta?

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_left_command.dart
> +    if (selectedWord!.trim().isEmpty) {
change `selectedWord!` to `selectedWord`

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +
`
if (node == null || delta == null) {
    return KeyEventResult.ignored;
  }
`
same as in arrow_left_command

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +    var startOfWord = selection.end.moveHorizontal(
use final here instead of var
`final startOfWord`

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +    final selectedWord = delta?.toPlainText().substring(
`delta` instead of `delta?`

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +          startOfWord!.offset,
remove `!`

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +    if (selectedWord!.trim().isEmpty) {
remove `!`

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +    var endOfWord = selection.end.moveHorizontal(
`final endOfWord`

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +    final selectedLine = delta?.toPlainText();
`
final selectedWord = delta.toPlainText().substring(
          selection.end.offset,
          endOfWord.offset,
        );
`
consistency

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +    );
`if (endOfWord == null) {
      return KeyEventResult.handled;
    }`
    
check endOfWord is null or not, imagine being at the end of line

2023-08-11 10:33 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
> +    if (selectedWord!.trim().isEmpty) {
use `selectedWord` instead of `selectedWord!`

2023-08-11 14:36 UTC, MayurSMahajan commented
Let me know when this PR is ready for review

2023-08-11 15:29 UTC, johansutrisno commented
Thanks @Xazin  and @MayurSMahajan for your code review, now this PR is ready to review.

2023-08-21 03:47 UTC, merged