fix: fixed the cursor not moving to next line after inserting divider
AppFlowy-IO/appflowy-editor pull request #371
Opened 2023-08-12 16:21 UTC by Mukund-Tandon

fixes: #370 
Before:
![ezgif com-video-to-gif (3)](https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/a0300983-0023-4c4a-8dd7-eba177b5c8a3)

After -

https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/0f0a2de1-533a-4356-8337-48323935b081

2023-08-12 16:54 UTC, MayurSMahajan requested changes
Great work! Can you add a test to assure this functionality, so that if it breaks in the future, we would know.

2023-08-12 17:02 UTC, Mukund-Tandon commented
> Great work! Can you add a test to assure this functionality, so that if it breaks in the future, we would know.

Ok,I will add them

2023-08-14 09:36 UTC, Xazin approved these changes

2023-08-17 05:12 UTC, LucasXu0 commented on lib/src/editor/block_component/divider_block_component/divider_block_component.dart
> +    // }
Why do you comment out this code?

2023-08-17 05:12 UTC, LucasXu0 commented on lib/src/editor/block_component/divider_block_component/divider_block_component.dart
> +  CursorStyle get cursorStyle => CursorStyle.borderLine;
Don't modify it

2023-08-17 06:02 UTC, Mukund-Tandon commented on lib/src/editor/block_component/divider_block_component/divider_block_component.dart
> +    // }
I am sorry ,forgot to uncomment it , I was just testing and understanding the code base

2023-08-24 05:31 UTC, MayurSMahajan approved these changes

2023-08-28 09:11 UTC, merged