feat: table html encoder and decoder added
AppFlowy-IO/appflowy-editor pull request #449
Opened 2023-09-11 14:47 UTC by alihassan143

2023-09-11 15:16 UTC, alihassan143 commented
@LucasXu0 you can review this pr

2023-09-13 02:36 UTC, LucasXu0 commented
@zoli Please take a look.

2023-09-13 08:16 UTC, zoli requested changes
Looks good to me except for the comments. @alihassan143 Thanks for the effort.

2023-09-13 08:16 UTC, zoli commented on lib/src/plugins/html/html_document_decoder.dart
> +    for (final data in element.children) {
I suggest to change this for loop to this:
```dart
for (final data in element.children) {
      Attributes attributes = {
        TableCellBlockKeys.colPosition: columnPosition,
        TableCellBlockKeys.rowPosition: rowPosition,
      };
      if (data.attributes.isNotEmpty) {
        final deltaAttributes = _getDeltaAttributesFromHTMLAttributes(
              element.attributes,
            ) ??
            {};
        attributes.addAll(deltaAttributes);
      }

      List<Node> children;
      if (data.children.isEmpty) {
        children = [paragraphNode(text: data.text)];
      } else {
        children = _parseTableSpecialNodes(data).toList();
      }

      final node = Node(
        type: TableCellBlockKeys.type,
        attributes: attributes,
        children: children,
      );

      nodes.add(node);
      columnPosition++;
    }
```

It's much cleaner.

2023-09-13 08:16 UTC, zoli commented on lib/src/plugins/html/html_document_decoder.dart
> +    AttributeType attributeType = AttributeType.none,
I don't get this. Is there anywhere calling `_getDeltaAttributesFromHTMLAttributes` with `attributeTyoe` other than none?

2023-09-13 08:16 UTC, zoli commented on lib/src/plugins/html/html_document_decoder.dart
> +enum AttributeType { table, tablerow, none }
I suggest a better name because at first, I made the mistake of thinking it had a relation to node attributes.

2023-09-13 09:08 UTC, alihassan143 commented on lib/src/plugins/html/html_document_decoder.dart
> +    AttributeType attributeType = AttributeType.none,
currently width and height of the table can be get from internal css other attribute currently not supported

2023-09-13 09:09 UTC, alihassan143 commented on lib/src/plugins/html/html_document_decoder.dart
> +            TableBlockKeys.colDefaultWidth: 60,
assert is already defined in the table block so i have to provide some default values

2023-09-13 09:45 UTC, alihassan143 commented
@zoli changes applied

2023-09-13 13:33 UTC, zoli commented on lib/src/plugins/html/html_document_decoder.dart
> +    AttributeType attributeType = AttributeType.none,
But you never call `_getDeltaAttributesFromHTMLAttributes` with `HtmlAttributeType.tablerow`, So what's the point? Is it for the future?

I think I'm not understanding something here.

2023-09-13 13:34 UTC, zoli commented on lib/src/plugins/html/html_document_decoder.dart
> +    HtmlAttributeType attributeType = HtmlAttributeType.none,
You never call _getDeltaAttributesFromHTMLAttributes with HtmlAttributeType.tablerow, So what's the point? Is it for the future?

I think I'm not understanding something here.

2023-09-20 13:32 UTC, zoli approved these changes
LGTM, Thanks.

2023-09-22 04:01 UTC, alihassan143 commented
@LucasXu0  kindly check the pr @zoli  approved the pr

2023-09-25 09:36 UTC, alihassan143 commented
@LucasXu0

2023-10-04 03:47 UTC, alihassan143 commented
@LucasXu0  any chance of this pr to be merged?

2023-10-22 13:59 UTC, merged