feat: add regex and case sensitive to `FindReplaceMenu`
AppFlowy-IO/appflowy-editor pull request #480
Opened 2023-09-18 12:48 UTC by sun-jiao

2023-09-18 13:16 UTC, Xazin commented on lib/src/editor/find_replace_menu/search_algorithm.dart
> +    }
```suggestion
    throw UnimplementedError();
```

2023-09-18 13:18 UTC, Xazin commented on lib/src/editor/find_replace_menu/search_service.dart
> +  void rFindAndHighlight(Pattern pattern, {bool unhighlight = false}) {
Can we name this a bit better? We have `findAndHighlight` and `rFindAndHighlight`, and the first one calls the second one.

2023-09-18 14:50 UTC, sun-jiao commented on lib/src/editor/find_replace_menu/find_replace_widget.dart
> +                'Cc',
It is used as an icon. Inspired by Jet-brains IDEs. How about extract it into an image asset?

![图片](https://github.com/AppFlowy-IO/appflowy-editor/assets/14086980/0b2d45b1-7473-49b9-bcb4-1a7413c18d69)

2023-09-18 15:00 UTC, MayurSMahajan requested changes

2023-09-18 15:00 UTC, MayurSMahajan commented on lib/src/editor/find_replace_menu/search_algorithm.dart
> +    if (pattern is String) {
@sun-jiao @Xazin, do we need to create a Mixture class?
If `DartBuiltin` works in all cases, we should just use that, since it is faster.
And keep `BoyerMoore` as an example for the developer if they want to implement their own algorithm.
Also then, we could remove the `BoyerMoore` implementation from the code and only show it in Docs as an example.

2023-09-18 15:00 UTC, sun-jiao commented on lib/src/editor/find_replace_menu/search_service.dart
> +  void rFindAndHighlight(Pattern pattern, {bool unhighlight = false}) {
Done. My fault. Previously I planned to separate plaint text and regex to two different methods. "r" stands for "regex". While latterly I forgot it and used the name in another way.

2023-09-18 15:00 UTC, sun-jiao commented on lib/src/editor/find_replace_menu/search_service.dart
> +  void rFindAndHighlight(Pattern pattern, {bool unhighlight = false}) {
Done. My fault. Previously I planned to separate plaint text and regex to two different methods. "r" stands for "regex". While latterly I forgot it and used the name in another way.

2023-09-18 15:02 UTC, sun-jiao commented on lib/src/editor/find_replace_menu/search_service.dart
> +  void rFindAndHighlight(Pattern pattern, {bool unhighlight = false}) {
Done. My fault. Previously I planned to separate plaint text and regex to two different methods. "r" stands for "regex". While latterly I forgot it and used the name in another way.

2023-09-18 15:17 UTC, sun-jiao commented on lib/src/editor/find_replace_menu/search_algorithm.dart
> +    if (pattern is String) {
In fact I have read some articles or papers on Boyer-Moore style regex search algorithm. But they're not as concise as the original Boyer-Moore. 

Rust community also has a similar issue. [rust-lang/regex#197](https://github.com/rust-lang/regex/issues/197)

2023-09-18 15:17 UTC, sun-jiao commented on lib/src/editor/find_replace_menu/search_algorithm.dart
> +class DartBuiltin extends SearchAlgorithm {
Done.

2023-09-18 15:24 UTC, sun-jiao commented on lib/src/editor/find_replace_menu/search_algorithm.dart
> +    if (pattern is String) {
They have already implemented it: [rust-lang/regex#419](https://github.com/rust-lang/regex/pull/419). I'll take a look tomorrow.

2023-09-18 15:58 UTC, sun-jiao commented on lib/src/editor/find_replace_menu/search_algorithm.dart
> +    if (pattern is String) {
I took a brief look and this still seems to be a plain text search algorithm, not regex. Even though it's in the regex carte.

2023-09-19 02:43 UTC, sun-jiao commented
I did some test for natural language.

```

late final String file;
final bm = BoyerMoore();
timer(String algorithmName, String target,
    Iterable<Match> Function(String target, String text) findFunction) {
  final start1 = DateTime.now().millisecondsSinceEpoch;
  final result = findFunction.call(target, file);
  final length = result.length;
  final end1 = DateTime.now().millisecondsSinceEpoch;
  print('$algorithmName finds $length matches, costs ${end1 - start1} milliseconds.');
}

Future<void> main() async {
  file = await File('data').readAsString();
  final targets = [
    "newspaper editor",
    "school girl",
    "the day after tomorrow",
    "United States",
    "Chinese",
    "native speaker",
    "very interesting",
    "disappeared",
    "a small compartment for holding papers",
    "in this important document"
  ];
  for (String target in targets) {
    print('Searching $target');
    timer('Built-in String', target, (target, text) => target.allMatches(text));
    timer('Built-in RegExp', target,
        (target, text) => RegExp(RegExp.escape(target)).allMatches(text));
    timer('Boyer-Moore    ', target, (target, text) => bm.searchMethod(target, text));
  }
}
```
result:
```
Searching newspaper editor
Built-in String finds 2 matches, costs 30 milliseconds.
Built-in RegExp finds 2 matches, costs 12 milliseconds.
Boyer-Moore     finds 2 matches, costs 25 milliseconds.
Searching school girl
Built-in String finds 1 matches, costs 26 milliseconds.
Built-in RegExp finds 1 matches, costs 15 milliseconds.
Boyer-Moore     finds 1 matches, costs 30 milliseconds.
Searching the day after tomorrow
Built-in String finds 1 matches, costs 29 milliseconds.
Built-in RegExp finds 1 matches, costs 17 milliseconds.
Boyer-Moore     finds 1 matches, costs 11 milliseconds.
Searching United States
Built-in String finds 143 matches, costs 21 milliseconds.
Built-in RegExp finds 143 matches, costs 13 milliseconds.
Boyer-Moore     finds 143 matches, costs 19 milliseconds.
Searching Chinese
Built-in String finds 201 matches, costs 22 milliseconds.
Built-in RegExp finds 201 matches, costs 10 milliseconds.
Boyer-Moore     finds 201 matches, costs 29 milliseconds.
Searching native speaker
Built-in String finds 1 matches, costs 26 milliseconds.
Built-in RegExp finds 1 matches, costs 13 milliseconds.
Boyer-Moore     finds 1 matches, costs 17 milliseconds.
Searching very interesting
Built-in String finds 1 matches, costs 22 milliseconds.
Built-in RegExp finds 1 matches, costs 16 milliseconds.
Boyer-Moore     finds 1 matches, costs 15 milliseconds.
Searching disappeared
Built-in String finds 14 matches, costs 24 milliseconds.
Built-in RegExp finds 14 matches, costs 9 milliseconds.
Boyer-Moore     finds 14 matches, costs 21 milliseconds.
Searching a small compartment for holding papers
Built-in String finds 1 matches, costs 32 milliseconds.
Built-in RegExp finds 1 matches, costs 9 milliseconds.
Boyer-Moore     finds 1 matches, costs 9 milliseconds.
Searching in this important document
Built-in String finds 1 matches, costs 28 milliseconds.
Built-in RegExp finds 1 matches, costs 17 milliseconds.
Boyer-Moore     finds 1 matches, costs 12 milliseconds.
```

2023-09-19 02:54 UTC, sun-jiao commented
[*WikiQA*](https://www.microsoft.com/en-us/download/details.aspx?id=52419&from=http%3A%2F%2Fresearch.microsoft.com%2Fapps%2Fmobile%2Fdownload.aspx%3Fp%3D4495da01-db8c-4041-a7f6-7984a4f6a905)

```
Searching "newspaper editor":
Built-in String finds 2 matches, costs 23 milliseconds.
Built-in RegExp finds 2 matches, costs 9 milliseconds.
Boyer-Moore     finds 2 matches, costs 19 milliseconds.

Searching "school girl":
Built-in String finds 1 matches, costs 19 milliseconds.
Built-in RegExp finds 1 matches, costs 9 milliseconds.
Boyer-Moore     finds 1 matches, costs 20 milliseconds.

Searching "United States":
Built-in String finds 3078 matches, costs 18 milliseconds.
Built-in RegExp finds 3078 matches, costs 14 milliseconds.
Boyer-Moore     finds 3078 matches, costs 15 milliseconds.

Searching "Chinese Civil War":
Built-in String finds 21 matches, costs 17 milliseconds.
Built-in RegExp finds 21 matches, costs 12 milliseconds.
Boyer-Moore     finds 21 matches, costs 11 milliseconds.

Searching "native speaker":
Built-in String finds 6 matches, costs 20 milliseconds.
Built-in RegExp finds 6 matches, costs 13 milliseconds.
Boyer-Moore     finds 6 matches, costs 13 milliseconds.

Searching "very interesting":
Built-in String finds 1 matches, costs 17 milliseconds.
Built-in RegExp finds 1 matches, costs 12 milliseconds.
Boyer-Moore     finds 1 matches, costs 12 milliseconds.

Searching "disappeared":
Built-in String finds 9 matches, costs 19 milliseconds.
Built-in RegExp finds 9 matches, costs 8 milliseconds.
Boyer-Moore     finds 9 matches, costs 17 milliseconds.

Searching "African Americans":
Built-in String finds 14 matches, costs 17 milliseconds.
Built-in RegExp finds 14 matches, costs 11 milliseconds.
Boyer-Moore     finds 14 matches, costs 13 milliseconds.

Searching "There are also":
Built-in String finds 18 matches, costs 17 milliseconds.
Built-in RegExp finds 18 matches, costs 9 milliseconds.
Boyer-Moore     finds 18 matches, costs 15 milliseconds.

Searching "nuclear power":
Built-in String finds 19 matches, costs 20 milliseconds.
Built-in RegExp finds 19 matches, costs 12 milliseconds.
Boyer-Moore     finds 19 matches, costs 14 milliseconds.
```

2023-09-19 13:40 UTC, MayurSMahajan commented
I think so, it will simplify the code and will be easier to maintain. But I think @Xazin is the best person to answer this.

2023-09-19 14:40 UTC, sun-jiao commented
@MayurSMahajan @Xazin Done. 

What should we do to the 'Cc' icon? Keep the text or extract it into an image asset?

2023-09-19 15:24 UTC, MayurSMahajan commented
did you try: `Icon(Icons.closed_caption)`. If you did not like that, then create an image asset.

2023-09-20 05:54 UTC, MayurSMahajan commented
> did you try: `Icon(Icons.closed_caption)`. If you did not like that, then create an image asset.

Oh I forgot that you wanted to use it for showing Case, silly me, please convert them to image assets then.

2023-09-21 04:37 UTC, sun-jiao commented
@MayurSMahajan @Xazin Done.

Already converted them to svg files. And I added some test cases for regex replace and case sensitive.

2023-09-21 04:39 UTC, MayurSMahajan approved these changes
Looks Good to me.

2023-09-26 12:56 UTC, sun-jiao commented
Hi, any updates on this?

2023-09-27 11:57 UTC, Xazin commented
I will take a look soon 👍

2023-10-02 18:20 UTC, Xazin commented
Hey @sun-jiao, sorry about the delay, my colleague was working on some improvements for the find-replace feature, so I was waiting to see how those changes would impact this PR.

Can you rebase on the latest `main`?

2023-10-04 11:42 UTC, sun-jiao commented
Hello, I am traveling during the China National Day holiday. I will update the branch as soon as possible after the trip.

2023-10-04 11:44 UTC, Xazin commented
> Hello, I am traveling during the China National Day holiday. I will update the branch as soon as possible after the trip.

No worries, hope you enjoy the trip 👌

2023-10-07 09:00 UTC, sun-jiao commented
@Xazin Already merged the main branch to this PR.

2023-10-10 07:53 UTC, LucasXu0 approved these changes

2023-10-10 07:53 UTC, merged