feat: = + > then ⇒
AppFlowy-IO/appflowy-editor pull request #523
Opened 2023-10-09 19:28 UTC by Gen1us1100

fixes: #2309

offers users to use '=' + '>' shortcut to input '⇒' into the editor.
Below video showcases the proper functioning 

https://github.com/AppFlowy-IO/appflowy-editor/assets/85549793/79ce67c9-b6d7-4742-892d-146178fd03a5

2023-10-09 19:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AppFlowy-IO/appflowy-editor?pullRequest=523) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AppFlowy-IO/appflowy-editor?pullRequest=523) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AppFlowy-IO/appflowy-editor?pullRequest=523) it.</sub>

2023-10-10 07:37 UTC, LucasXu0 commented
@Gen1us1100 Please add tests to cover this functionality. You can refer to the `format_bold_test.dart`.

2023-10-10 07:56 UTC, Xazin commented on lib/src/editor/editor_component/service/shortcuts/character_shortcut_events/format_double_characters/format_equal_greater_character.dart
> +Future<bool> handleEqualGreaterReplacement({
```suggestion
// TODO(Xazin): Combine two character replacement methods into
//  a helper function
Future<bool> handleEqualGreaterReplacement({
```

2023-10-20 16:38 UTC, Gen1us1100 commented
hey, @LucasXu0 I have tried adding tests for the stated feature, do check it out!

2023-10-21 15:29 UTC, MayurSMahajan requested changes
The file location is indeed correct. Nice clean code.

2023-10-21 15:29 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/character_shortcut_events/format_double_characters/format_equal_greater_character.dart
> +// ///
No need to commend the documentation comments.

2023-10-21 15:29 UTC, MayurSMahajan commented on lib/src/editor/editor_component/service/shortcuts/character_shortcut_events/format_double_characters/format_equal_greater_character.dart
> +// ///
So I mean that this: 

```dart
// /// format '=' + '>' into an ⇒ 
// ///
// /// - support
// ///   - desktop
// ///   - mobile
// ///   - web
// ///
```

should be:

```dart
/// format '=' + '>' into an ⇒ 
///
/// - support
///   - desktop
///   - mobile
///   - web
///
```

2023-10-21 15:29 UTC, MayurSMahajan commented on test/new/service/shortcuts/character_shortcut_events/double_characters_shortcut_events/format_equal_greater_test.dart
> +    });
great job! add more tests like:

1. executing this in a non-empty paragraph.
2. try doing undo and redo after inserting this.

2023-10-24 06:07 UTC, merged