fix:Solve the left and right key bug.
AppFlowy-IO/appflowy-editor pull request #584
Opened 2023-11-09 08:06 UTC by q200892907

Solve the left and right key bug. When adding an input box at the head or tail of the editor, it cannot be moved.

2023-11-09 08:09 UTC, Xazin approved these changes
CC @LucasXu0

2023-11-09 09:12 UTC, Xazin requested changes

2023-11-09 09:12 UTC, Xazin commented on lib/src/editor/editor_component/service/keyboard_service_widget.dart
> +    editorState.service.selectionService.registerGestureInterceptor(interceptor);
Seems like your formatting options are different than default 80 character line length.

2023-11-14 02:32 UTC, LucasXu0 commented
@q200892907 The format step failed. PTAL.

2023-11-14 09:34 UTC, q200892907 commented
> @q200892907 The format step failed. PTAL.

Restored default format

2023-11-15 01:55 UTC, merged