feat: abstract toolbar item icon sizes to editor style
AppFlowy-IO/appflowy-editor pull request #81
Opened 2023-04-14 10:04 UTC by alihassan143

#76

2023-04-14 12:36 UTC, LucasXu0 commented on lib/src/extensions/image_node_extension.dart
> +    final selection = service.selectionService.currentSelection.value;
If the selection is not collapsed, it should also return.

2023-05-08 04:34 UTC, alihassan143 commented
@LucasXu0 kindly check this pr

2023-05-08 12:18 UTC, Xazin requested changes

2023-05-08 12:18 UTC, Xazin commented on lib/src/render/image/image_upload_widget.dart
> +    if (selection.isCollapsed) {
```
if (selection == null || selection.isCollapsed) {
  return;
}
```
And weren't you supposed to add this check in the insert image handler extension?

2023-05-20 06:58 UTC, closed without merging